[mysql]
host = ""
db = ""
[mysql.root]
username = "root"
password = ''

[mysql.admin]
username = "admin"
password = ''

[mysql.builder]
username = "builder"
password = ''

[mysql.writer]
username = "writer"
password = ''

[mysql.reader]
username = "reader"
password = ''

[z]
username="z"
